ARG ROS_DISTRO=iron

FROM docker.io/ros:${ROS_DISTRO}

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
  python3-colcon-common-extensions \
  && rm -rf /var/lib/apt/lists/*

RUN echo<<EOT >> /root/.bashrc \
  source /opt/ros/${ROS_DISTRO}/setup.bash \
  EOT
