- name: Ensure development environment
  hosts: localhost
  gather_facts: false

  vars:
    cwd: "{{ playbook_dir }}/.."
    tmp_dir: "{{ cwd }}/tmp"

  handlers:
    - name: Prune podman
      containers.podman.podman_prune:
        system: true
      listen: podman_prune

  tasks:
    - name: Gather minimum facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - env

    - name: Ensure tmp directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure bash_history
      ansible.builtin.file:
        path: "{{ tmp_dir }}/.bash_history"
        state: touch
        mode: "0600"

    - name: Ensure podman devel container is {{ container_state }}
      containers.podman.podman_container:
        name: ros2-devel
        image: ros2-devel:latest
        volume:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - "{{ cwd }}/ws:/ws:z"
          - "{{ tmp_dir }}/.bash_history:/root/.bash_history:z"
        network_mode: host
        env:
          DISPLAY: "{{ ansible_env['DISPLAY'] }}"
        stop_signal: 9
        security_opt:
          - label=type:container_runtime_t
        command:
          - tail
          - -f
          - /dev/null
        state: "{{ container_state }}"
      notify: podman_prune

# vim: ft=yaml.ansible
